version: '3.4'

networks:
  metrics:

services:
  influxdb:
    hostname: influxdb
    container_name: influxdb
    image: influxdb:1.8
    networks:
      - metrics
    environment:
      - INFLUXDB_DB=k6

  grafana:
    hostname: grafana
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - metrics
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  # k6:
  #   image: grafana/k6:latest
  #   networks:
  #     - k6
  #   ports:
  #     - "6565:6565"
  #   command: "run -a 'localhost:6001' /scripts/dequeue.js"
  #   environment:
  #     - K6_OUT=influxdb=http://influxdb:8086/k6
  #   depends_on:
  #     - influxdb
  #   volumes:
  #     - ../k6-scripts:/scripts