apiVersion: 1

datasources:
  - name: dotnet
    type: influxdb
    access: proxy
    database: k6dotnet
    orgId: 1
    url: http://influxdb:8086
    isDefault: false

  - name: golang
    type: influxdb
    access: proxy
    database: k6go
    orgId: 1
    url: http://influxdb:8086
    isDefault: true
