version: '3.4'

networks:
  metrics:

services:
  influxdb:
    hostname: influxdb
    container_name: influxdb
    image: influxdb:1.8
    networks:
      - metrics
    volumes:
      - ./influx_init.iql:/docker-entrypoint-initdb.d/influx_init.iql/

  grafana:
    hostname: grafana
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - metrics
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/